[package]
name = "lienv"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lienv"
crate-type = ["cdylib"]

[dependencies]
fsize = "1.0.0"
lazy_static = "1.4.0"
pyo3 = "0.19.0"
